### PR TITLE
drone: do not publish for pull requests

### PR DESCRIPTION
**Pull request by tcely**
/cc @clandmeter @mor1

### CODE REVIEW

**Comment by mor1** [comment]
Not familiar with drone configs, but not publishing images for pull requests certainly seems the right thing to do so merging. Thanks!

**Comment by clandmeter** [comment]
You can also disable this in github hook settings.

**Comment by tcely** [comment]
@mor1 The yaml file needs to be regenerated too.

**Comment by mor1** [comment]
@tcely Sorry-- no idea how to do that! :) /cc @clandmeter

**Comment by tcely** [comment]
> Sorry-- no idea how to do that!

I found out and put it in the `Makefile` with #29.

**Pull request merged**
