### PR TITLE
dabuild: `docker pull` in preference to `apk upgrade`

### PR DESCRIPTION
**Pull request by mor1**

### CODE REVIEW

**Comment by clandmeter** [comment]
I'm on mobile so i could be wrong here, but why would this be better or
faster? World would be as old as the image would be so it would still need
an apk upgrade to make the system updated?

**Comment by tcely** [comment]
The key here is that the built image will control instead of the base image.

For this to be helpful, all the images will need to be rebuilt whenever an included package is upgraded.

**Comment by mor1** [comment]
@clandmeter Better/faster because the download of the image with the up-to-date packages in happens only the first time the image is used after its been updated. Subsequent invocations of `docker pull` will observe that the layers are all the same and not download anything. In contrast, putting `apk upgrade` in `entrypoint.sh` means that the apk packages are updated every time the container is created (every `docker run`), and because `docker run` only pulls the image once (rather than every time it's updated) that `apk upgrade` will get executed very frequently.

**Comment by mor1** [comment]
@tcely Yes, I thought that was something that had been considered -- have the Drone CI rebuild the images every time a patch to aports is merged. (Roughly.) That means that the images used by `dabuild` for building packages in development are always as up-to-date as possible, but also that they're always identical between different users.

**Comment by clandmeter** [comment]
apk upgrade and docker pull are both slow processes. entrypoint.sh is also the final step before abuild is triggered, so to make sure you are building against the lastest apk index one should upgrade system before a build. This is similar as our builder and CI.

The problem here is that the apk index is behind and the upgrade needs to pull multiple packages to satisfy updated world.

To fix this we have a few options:

1. Update world as we do now in entrypoint but its slow.
2. update docker image on each aports change (terrible abuse of cpu cycles)
This means on each build we need to pull the new image (if aports changed) which is also slow depending on the used registry.
3. regularly update the image (ones a week) and fetch a new one when needed, but between updates we use apk cache which will pull packages cached on local filesystem. This should limit docker pull and speed up updating world because it uses local cache instead of remote repository. Another big advantage is that when you need to pull in packages in a regular basis they will already be cached. This makes repeated installations much faster.

**Comment by clandmeter** [comment]
@mor1 #31 in combination with your docker pull should be enough to keep the image uptodate and not introduce too much overhead. Each package that gets pushed after a new docker image creation will be pulled and cached in apkcache which is reusable. It also caches build deps which are also reusable.

If you remove apk upgrade from entrypoint.sh you will loose the insurance of an uptodate system (packages that are updated after the latest docker build).

**Comment by mor1** [comment]
(That auto-close was premature; am looking at #31 now. I think something like that is the right solution. Thanks!)

**Pull request closed without merging**
