### PR TITLE
entrypoint: copy public keys to /etc/apk/keys directory

### LINKED ISSUE #15: abuild-keygen generated keys are not preserved between runs
https://github.com/alpinelinux/docker-abuild/blob/c5508e242ebc64e0c5018ac115c3dff8d3ae77ba/entrypoint.sh#L13

I feel that this code will run every time as the check will return true all time as this directory will be not preserved between runs. This could lead to that with each run the new key pair will be generated and already signed index files will be rendered as un-trusted as they will be signed with one key pair and later they will be intended to be signed with fresh generated key pair.

Maybe we can move key generation to Dockerfile?

### PR DESCRIPTION
**Pull request by tcely**
Resolves alpinelinux/docker-abuild#15

### CODE REVIEW

**Comment by mor1** [comment]
Thanks!

**Comment by OTLabs** [comment]
Does `"$HOME/.abuild/abuild.conf"` have support for multiple `"$PACKAGER_PRIVKEY"`?

If not - we need to copy just one key corresponding to `"$PACKAGER_PRIVKEY"`. What you think?

**Comment by tcely** [comment]
You need to consider key rotation here.

Not all of the packages were signed with the most recent key, but they are in my index and I want to be able to install them.

**Comment by OTLabs** [comment]
Oh, ok, thanks!

**Pull request merged**
